language: node_js
node_js:
  - "node"
install:
  - npm install
script: 
  - gulp build || travis_terminate 1
  - gulp unit || travis_terminate 1
  - gulp coveralls || travis_terminate 1
cache:
  directories:
  - node_modules