language: node_js
node_js:
  - "node"
install:
  - cd ..
  - git clone --branch=TRAVIS_BRANCH https://github.com/unitejs/framework.git framework
  - cd framework
  - npm link
  - cd ..
  - git clone --branch=TRAVIS_BRANCH https://github.com/unitejs/cli-core.git cli-core
  - cd cli-core
  - npm link "unitejs-framework"
  - npm link
  - cd ..
  - git clone --branch=TRAVIS_BRANCH https://github.com/unitejs/engine.git engine
  - cd engine
  - npm link "unitejs-framework"
  - npm link
  - cd ../cli
  - npm install gulp -g
  - npm link "unitejs-framework" "unitejs-cli-core" "unitejs-engine"
  - npm install
script: 
  - gulp build || travis_terminate 1
  - gulp unit || travis_terminate 1
  - gulp coveralls || travis_terminate 1
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/18d04b26e3da5f9fa9dc
    on_success: change
    on_failure: always
    on_start: never
