language: node_js
node_js:
  - "node"
install:
  - npm install
script: 
  - gulp build || travis_terminate 1
  - gulp unit || travis_terminate 1
  - gulp coveralls || travis_terminate 1
cache:
  directories:
  - node_modules
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/18d04b26e3da5f9fa9dc
    on_success: change
    on_failure: always
    on_start: never